"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/client";
export function LoginForm() {
 const router = useRouter(); const [visible,setVisible]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setLoading(true); const data=new FormData(e.currentTarget); try { const supabase=createClient(); const {error}=await supabase.auth.signInWithPassword({email:String(data.get("email")),password:String(data.get("password"))}); if(error) throw error; router.replace("/dashboard"); router.refresh(); } catch(err) { setError(err instanceof Error ? err.message : "Não foi possível autenticar."); } finally {setLoading(false)} }
 return <form onSubmit={submit} className="space-y-5"><div><label className="mb-2 block text-sm font-semibold text-slate-700" htmlFor="email">E-mail institucional</label><div className="relative"><Mail className="absolute left-3.5 top-3.5 text-slate-400" size={17}/><Input className="pl-10" id="email" name="email" type="email" autoComplete="email" placeholder="usuario@instituicao.mil.br" required/></div></div><div><div className="mb-2 flex justify-between"><label className="text-sm font-semibold text-slate-700" htmlFor="password">Senha</label><Link href="/esqueci-senha" className="text-xs font-semibold text-emerald-800 hover:underline">Esqueci minha senha</Link></div><div className="relative"><LockKeyhole className="absolute left-3.5 top-3.5 text-slate-400" size={17}/><Input className="px-10" id="password" name="password" type={visible?"text":"password"} autoComplete="current-password" required/><button type="button" onClick={()=>setVisible(!visible)} aria-label="Mostrar senha" className="absolute right-3.5 top-3 text-slate-400">{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button className="w-full bg-emerald-950 hover:bg-emerald-900" disabled={loading}>{loading&&<LoaderCircle className="animate-spin" size={18}/>}Acessar ambiente seguro</Button><p className="text-center text-xs leading-5 text-slate-500">Acesso restrito a usuários autorizados. Todas as ações são registradas para fins de auditoria.</p></form>
}
